# Generated by Django 3.1.7 on 2022-01-15 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0001_initial'),
        ('super_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineinfo',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='givemedicinetopatient',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_admin.medicineinfo'),
        ),
        migrations.AddField(
            model_name='givemedicinetopatient',
            name='patient_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.makeappointment'),
        ),
    ]
